"""add quiz config columns

Revision ID: 00c544588def
Revises: 3d3f6e1bf8fc
Create Date: 2026-07-31 11:32:56.511331
"""
from alembic import op
import sqlalchemy as sa


revision = '00c544588def'
down_revision = '3d3f6e1bf8fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.add_column('quiz_questions', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('quizzes', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('hints_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'hints_enabled')
    op.drop_column('quizzes', 'time_limit_minutes')
    op.drop_column('quiz_questions', 'hint')
    op.drop_column('quiz_questions', 'question_type')
    # ### end Alembic commands ###
