"""add flashcards, notes, mindmaps, roadmaps

Revision ID: 1da286584713
Revises: 00c544588def
Create Date: 2026-07-31 16:32:48.658393
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1da286584713'
down_revision = '00c544588def'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('json_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_owner_id'), 'roadmaps', ['owner_id'], unique=False)
    op.drop_column('quiz_questions', 'question_type')
    op.drop_column('quiz_questions', 'hint')
    op.drop_column('quizzes', 'hints_enabled')
    op.drop_column('quizzes', 'time_limit_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('time_limit_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('hints_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quiz_questions', sa.Column('hint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz_questions', sa.Column('question_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roadmaps_owner_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
