"""sync schema

Revision ID: e3f0e824bc37
Revises: 1da286584713
Create Date: 2026-08-01 15:02:23.220003
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e3f0e824bc37'
down_revision = '1da286584713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('quiz_questions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.add_column('quiz_questions', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('quizzes', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('hints_enabled', sa.Boolean(), nullable=True))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('quizzes', 'hints_enabled')
    op.drop_column('quizzes', 'time_limit_minutes')
    op.drop_column('quiz_questions', 'hint')
    op.drop_column('quiz_questions', 'question_type')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
